### PR TITLE
homework_6 & homework_5.sql (all questions completed), homework_4.sql (completed)

### PR DESCRIPTION
**Pull request by rktakk**
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by SidraBushra** [comment]
Hw4 is good, passed

**Comment by SidraBushra** [comment]
HW5 is incomplete.

**Comment by rktakk** [comment]
> HW5 is incomplete.

I've completed the missing question.

**Comment by SidraBushra** [comment]
HW5, 6 Marked, Passed.

**Pull request closed without merging**
